// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlPibb5rsCftsmcUwy_-76Ah1nIWZthKk',
    appId: '1:384858750453:web:ebfc23701dc73636d174bc',
    messagingSenderId: '384858750453',
    projectId: 'admin-26150',
    authDomain: 'admin-26150.firebaseapp.com',
    storageBucket: 'admin-26150.firebasestorage.app',
    measurementId: 'G-ELTW9NZYZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD39qNpcMIDTWuid-N_xzLmssfRRxyUrLQ',
    appId: '1:384858750453:android:84b199cf2b33da5dd174bc',
    messagingSenderId: '384858750453',
    projectId: 'admin-26150',
    storageBucket: 'admin-26150.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOq5QJgOntt9IHtOsIxt9nLJdkIEx9Jes',
    appId: '1:384858750453:ios:4e1033fe06d32368d174bc',
    messagingSenderId: '384858750453',
    projectId: 'admin-26150',
    storageBucket: 'admin-26150.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOq5QJgOntt9IHtOsIxt9nLJdkIEx9Jes',
    appId: '1:384858750453:ios:4e1033fe06d32368d174bc',
    messagingSenderId: '384858750453',
    projectId: 'admin-26150',
    storageBucket: 'admin-26150.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlPibb5rsCftsmcUwy_-76Ah1nIWZthKk',
    appId: '1:384858750453:web:d5c9e364cd39f185d174bc',
    messagingSenderId: '384858750453',
    projectId: 'admin-26150',
    authDomain: 'admin-26150.firebaseapp.com',
    storageBucket: 'admin-26150.firebasestorage.app',
    measurementId: 'G-MXN9F1P6C0',
  );
}
